export enum TotalKey {
  INVALID = 0,
  ALL_MEMBER_CNT = 1,
  NEW_MEMBER_CNT = 2,
  ACTIVE_MEMBER_CNT = 3,
  ALL_FILE_CNT = 4,
  ALL_EMOJI_CNT = 5,
  ALL_COMMENT_CNT = 6,
  ALL_SHARE_CNT = 7,
  CREATE_FILE_CNT = 8,
  CREATE_EMOJI_CNT = 9,
  CREATE_COMMENT_CNT = 10,
  CREATE_SHARE_CNT = 11,
}
